export const MOCK_PROFILES = [
  {
    id: 1,
    uid: "SR-9281-K",
    name: "Ayesha Rahman",
    age: 24,
    gender: "female",
    city: "London",
    country: "UK",
    image: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?q=80&w=687&auto=format&fit=crop",
    occupation: "Medical Doctor",
    education: "MBBS",
    religiosity: "Moderate",
    sect: "Sunni",
    salary: "£45k/year",
    hobbies: "Reading, Islamic history, and mountain hiking.",
    salah: "5 times/day",
    height: "165cm",
    weight: "58kg"
  },
  {
    id: 2,
    uid: "SR-4729-M",
    name: "Zainab Malik",
    age: 27,
    gender: "female",
    city: "Toronto",
    country: "Canada",
    image: "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?q=80&w=686&auto=format&fit=crop",
    occupation: "Software Engineer",
    education: "Masters in CS",
    religiosity: "Strict",
    sect: "Sunni",
    salary: "$95k/year",
    hobbies: "Coding, Arabic calligraphy, and community service.",
    salah: "5 times/day",
    height: "162cm",
    weight: "55kg"
  },
  {
    id: 3,
    uid: "SR-1034-O",
    name: "Omar Farooq",
    age: 30,
    gender: "male",
    city: "Dubai",
    country: "UAE",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=687&auto=format&fit=crop",
    occupation: "Investment Banker",
    education: "MBA",
    religiosity: "Moderate",
    sect: "Sunni",
    salary: "$120k/year",
    hobbies: "Horse riding, charity work, and learning Quran.",
    salah: "5 times/day",
    height: "182cm",
    weight: "80kg"
  }
];